"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowUpRight, Command, ExternalLink, Menu, Search, Terminal, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { currentFocus, education, experience, personalInfo, projects, siteLinks, skillGroups, skillProjectLinks, type Project } from "../data/site";

const HeroScene = dynamic(() => import("./scene"), { ssr: false, loading: () => <div className="scene-fallback" aria-hidden="true" /> });
const navItems = [{ id: "about", label: "About" }, { id: "projects", label: "Projects" }, { id: "experience", label: "Experience" }, { id: "skills", label: "Skills" }, { id: "contact", label: "Contact" }];
const fadeUp = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } };

function TiltCard({ children }: { children: React.ReactNode }) {
  const [style, setStyle] = useState<React.CSSProperties>({});
  return <article className="project-card-tilt" style={style} onMouseMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); setStyle({ transform: `perspective(900px) rotateX(${((e.clientY - r.top) / r.height - .5) * -3}deg) rotateY(${((e.clientX - r.left) / r.width - .5) * 3}deg)` }); }} onMouseLeave={() => setStyle({})}>{children}</article>;
}

function ProjectVisual({ project }: { project: Project }) {
  return <div className={`project-visual visual-${project.visual}`} aria-hidden="true">
    <span className="project-number">{project.number}</span>
    {project.visual === "game" && <div className="game-board">{["X", "", "O", "", "X", "", "O", "", ""].map((v, i) => <span key={i}>{v}</span>)}</div>}
    {project.visual === "data" && <><div className="waveform">⌁⌁⌁⌁⌁⌁⌁</div><div className="data-readout">160 RUNS <b>·</b> 28 ANOMALIES</div><i className="sensor sensor-one" /><i className="sensor sensor-two" /></>}
    {project.visual === "kernel" && <div className="terminal-visual"><span>$ qemu-system-aarch64</span><span>EL1  pc: 0x40080000</span><span>boot sequence: ok_</span></div>}
    {project.visual === "rag" && <div className="rag-flow"><span>PDF</span><b>→</b><span>VECTORS</span><b>→</b><span>ANSWER</span></div>}
    {project.visual === "cloud" && <div className="cloud-flow"><span>REACT</span><b>↓</b><span>SPRING API</span><b>↓</b><span>MYSQL · REDIS</span></div>}
  </div>;
}

export default function Portfolio() {
  const reduced = useReducedMotion();
  const [menuOpen, setMenuOpen] = useState(false), [palette, setPalette] = useState(false), [terminalOpen, setTerminalOpen] = useState(false);
  const [terminalInput, setTerminalInput] = useState(""), [terminalOutput, setTerminalOutput] = useState<string[]>([]), [expanded, setExpanded] = useState<string | null>(null);
  const [progress, setProgress] = useState(0), [active, setActive] = useState("about"), [spotlight, setSpotlight] = useState({ x: -500, y: -500 }), [highlightedSkill, setHighlightedSkill] = useState<string | null>(null);
  const reveal = reduced ? undefined : { once: true, amount: .16 };
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setPalette((v) => !v); } if (e.key === "Escape") { setPalette(false); setTerminalOpen(false); } };
    const onScroll = () => { const max = document.documentElement.scrollHeight - innerHeight; setProgress(max ? scrollY / max * 100 : 0); };
    const onPointer = (e: PointerEvent) => { if (matchMedia("(min-width: 900px) and (pointer: fine) and (prefers-reduced-motion: no-preference)").matches) setSpotlight({ x: e.clientX, y: e.clientY }); };
    addEventListener("keydown", onKey); addEventListener("scroll", onScroll, { passive: true }); addEventListener("pointermove", onPointer);
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: "-30% 0px -60% 0px" });
    navItems.forEach(({ id }) => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => { removeEventListener("keydown", onKey); removeEventListener("scroll", onScroll); removeEventListener("pointermove", onPointer); observer.disconnect(); };
  }, []);
  const commands = useMemo(() => [["Home", "#top"], ...navItems.map((x) => [x.label, `#${x.id}`] as const), ["Open Resume", siteLinks.resume], ["GitHub", siteLinks.github], ["LinkedIn", siteLinks.linkedin], ["Email Me", siteLinks.email]] as const, []);
  const runTerminal = (value: string) => { const command = value.trim().toLowerCase(); const responses: Record<string, string> = { help: "whoami  projects  skills  experience  contact  clear", whoami: "Raju Kumar Paswan\nComputer Science @ UTA\nSoftware Engineer • Builder", projects: "3D Tic Tac Toe · OperatorLoop · AArch64 Teaching Kernel Lab", skills: "Software engineering · AI/ML · cloud · systems · full-stack", experience: "Student Technical Assistant — Academic Technology, UTA OIT", contact: personalInfo.email, clear: "" }; setTerminalOutput((old) => command === "clear" ? [] : [...old, `> ${value}`, responses[command] ?? "Command not found. Type help for supported commands."]); setTerminalInput(""); };
  const resumeLink = <a className="text-link resume-link" href={siteLinks.resume} target="_blank" rel="noopener noreferrer">Resume <ArrowUpRight size={16} /></a>;
  return <main style={{ ["--spot-x" as string]: `${spotlight.x}px`, ["--spot-y" as string]: `${spotlight.y}px` }}>
    <div className="scroll-progress" style={{ width: `${progress}%` }} /><div className="spotlight" aria-hidden="true" />
    <header className="site-header"><a className="wordmark" href="#top" aria-label="RKP home">RKP<span>.</span></a><nav className={menuOpen ? "main-nav is-open" : "main-nav"} aria-label="Main navigation">{navItems.map((item) => <a className={active === item.id ? "active" : ""} href={`#${item.id}`} key={item.id} onClick={() => setMenuOpen(false)}>{item.label}</a>)}</nav><div className="header-actions"><button className="palette-trigger" onClick={() => setPalette(true)} aria-label="Open command palette"><Command size={14} /> K</button><a className="header-contact" href="#contact">Let&apos;s talk <ArrowUpRight size={15} /></a><button className="menu-toggle" type="button" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen((v) => !v)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <section className="hero section-shell" id="top"><div className="hero-copy"><motion.p className="eyebrow" initial={reduced ? false : "hidden"} animate="visible" variants={fadeUp}>COMPUTER SCIENCE • SOFTWARE ENGINEERING</motion.p><motion.h1 initial={reduced ? false : "hidden"} animate="visible" variants={fadeUp}>Raju Kumar <span>Paswan</span></motion.h1><motion.h2 initial={reduced ? false : "hidden"} animate="visible" variants={fadeUp}>Building intelligent software<br />and interactive digital experiences.</motion.h2><p className="hero-intro">{personalInfo.intro}</p><div className="hero-actions"><a className="button-primary" href="#projects">View Projects <ArrowDown size={16} /></a>{resumeLink}<a className="text-link" href={siteLinks.github} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={16} /></a></div></div><div className="hero-art"><div className="art-grid" /><HeroScene /></div></section>
    <motion.section className="section-shell split-section" id="about" initial="hidden" whileInView="visible" viewport={reveal} variants={fadeUp}><div className="section-label"><span>01</span> About</div><div className="about-content"><h2>Curious by default.<br /><span>Intentional by design.</span></h2><div className="about-grid"><div><p className="large-copy">I&apos;m a Computer Science student at The University of Texas at Arlington with a minor in Data Science. I enjoy working across the stack — from low-level systems and debugging to AI-powered applications, cloud infrastructure, and modern web experiences.</p><div className="currently"><strong>Currently</strong>{currentFocus.map((item) => <span key={item}>{item}</span>)}</div></div><div className="portrait-wrap"><div className="portrait-frame"><Image className="portrait" src="/images/raju-profile.jpg" alt="Raju Kumar Paswan" width={280} height={350} /></div></div></div><div className="education"><div><small>Education</small><strong>{education.school}</strong><span>{education.degree}<br />{education.minor}</span></div><div><small>Coursework</small><span>{education.coursework.join(" · ")}</span></div><div><small>Organizations</small><span>{education.organizations.join(" · ")}</span></div></div></div></motion.section>
    <section className="work-section" id="projects"><div className="section-shell"><div className="section-heading"><div><div className="section-label"><span>02</span> Projects</div><h2>Selected systems<br /><span>and experiments.</span></h2></div><p>Built, documented, and still being explored.</p></div><div className="project-grid">{projects.map((project) => <TiltCard key={project.title}><ProjectVisual project={project} /><div className="project-info"><div className="project-title-row"><div><h3>{project.title}</h3><p>{project.description}</p></div><span className={`status ${project.status === "Completed" ? "complete" : ""}`}>{project.status}</span></div><div className="project-meta"><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links">{project.github && <a href={project.github} target="_blank" rel="noopener noreferrer">GitHub <ExternalLink size={12} /></a>}{project.liveDemo && <a href={project.liveDemo} target="_blank" rel="noopener noreferrer">Live Demo <ExternalLink size={12} /></a>}</div></div><button className="details-button" onClick={() => setExpanded(expanded === project.title ? null : project.title)}>Case study <span>{expanded === project.title ? "−" : "+"}</span></button>{expanded === project.title && <div className="case-study"><p><b>Problem</b>{project.problem}</p><p><b>Approach</b>{project.approach}</p><p><b>Engineering decisions</b>{project.decisions}</p><p><b>Outcome / current status</b>{project.outcome}</p></div>}</div></TiltCard>)}</div></div></section>
    <motion.section className="section-shell split-section experience-section" id="experience" initial="hidden" whileInView="visible" viewport={reveal} variants={fadeUp}><div className="section-label"><span>03</span> Experience</div><div className="experience-content"><h2>A timeline of<br /><span>technical support.</span></h2><div className="timeline">{experience.slice().reverse().map((item) => <article className="timeline-item" key={item.title}><div className="timeline-marker" /><div><small>{item.date}</small><h3>{item.title}</h3><p className="timeline-company">{item.company}</p><ul>{item.responsibilities.map((line) => <li key={line}>{line}</li>)}</ul><div className="tag-list">{item.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div></article>)}</div></div></motion.section>
    <motion.section className="section-shell split-section skills-section" id="skills" initial="hidden" whileInView="visible" viewport={reveal} variants={fadeUp}><div className="section-label"><span>04</span> Skills</div><div className="skills-content"><h2>Tools for turning<br /><span>questions into systems.</span></h2><p className="skills-note">Focus a highlighted skill to see where it connects in the project set.</p><div className="skill-grid">{skillGroups.map((group) => <div className="skill-group" key={group.label}><small>{group.label}</small><span className="skill-state">{group.state}</span><div>{group.items.map((item) => { const related = skillProjectLinks[item as keyof typeof skillProjectLinks]; return <button className={highlightedSkill === item ? "skill-chip is-highlighted" : "skill-chip"} key={item} type="button" onFocus={() => setHighlightedSkill(item)} onMouseEnter={() => setHighlightedSkill(item)} onBlur={() => setHighlightedSkill(null)} onMouseLeave={() => setHighlightedSkill(null)}>{item}{related ? <span className="skill-related">{related.join(" · ")}</span> : null}</button>; })}</div></div>)}</div></div></motion.section>
    <section className="contact-section" id="contact"><div className="section-shell contact-inner"><div><div className="section-label"><span>05</span> Contact</div><h2>Have a system<br /><span>worth building?</span></h2></div><div><p>Open to thoughtful engineering conversations, collaborations, and opportunities.</p><div className="contact-actions"><a className="button-primary" href={siteLinks.email}>Email me <ArrowUpRight size={16} /></a><a className="text-link" href={siteLinks.github} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={16} /></a><a className="text-link" href={siteLinks.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={16} /></a>{resumeLink}</div></div></div></section>
    <footer className="site-footer section-shell"><span className="wordmark">RKP<span>.</span></span><span>Designed &amp; Developed by Raju Kumar Paswan<br />© {new Date().getFullYear()} Raju Kumar Paswan</span><div><a href={siteLinks.github} target="_blank" rel="noopener noreferrer">GitHub</a><a href={siteLinks.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a>{resumeLink}</div></footer>
    <button className="terminal-trigger" onClick={() => setTerminalOpen(true)} aria-label="Open safe terminal"><Terminal size={15} /> terminal</button>
    <AnimatePresence>{palette && <div className="overlay" onClick={() => setPalette(false)}><motion.div className="palette" role="dialog" aria-label="Command palette" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} onClick={(e) => e.stopPropagation()}><div className="palette-search"><Search size={16} /><input autoFocus placeholder="Jump to..." /></div>{commands.map(([label, href]) => <a key={label} href={href} target={href === siteLinks.resume || href.startsWith("http") ? "_blank" : undefined} rel={href === siteLinks.resume || href.startsWith("http") ? "noopener noreferrer" : undefined} onClick={() => setPalette(false)}>{label}<ArrowUpRight size={13} /></a>)}</motion.div></div>}{terminalOpen && <div className="overlay" onClick={() => setTerminalOpen(false)}><motion.div className="terminal-modal" role="dialog" aria-label="Safe terminal" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} onClick={(e) => e.stopPropagation()}><div className="terminal-head"><span>RKP terminal</span><button onClick={() => setTerminalOpen(false)} aria-label="Close terminal"><X size={16} /></button></div><div className="terminal-output">{terminalOutput.map((line, i) => <pre key={i}>{line}</pre>)}</div><form onSubmit={(e) => { e.preventDefault(); runTerminal(terminalInput); }}><span>&gt;</span><input autoFocus value={terminalInput} onChange={(e) => setTerminalInput(e.target.value)} aria-label="Terminal command" /></form></motion.div></div>}</AnimatePresence>
  </main>;
}
